version: 2
jobs:
  build:
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: testimio/docker-cli
    steps:
      - run: mkdir -p $CIRCLE_TEST_REPORTS/testim/
      - run: testim --token "hrbpRydenEOSQVxtDLDiSUZuHmu5e79KUB1Z2KdEtnpXOvSNVf" --project "xWparmpTPWgDNk8sUzpe" --grid "Testim-Grid" --chrome-extra-args "use-fake-device-for-media-stream" --mode "extension" --branch "Aniket" --label "Aniket" --report-file $CIRCLE_TEST_REPORTS/testim/results.xml
      - store_artifacts:
          path: /tmp/circleci-test-results
      - store_test_results:
          path: /tmp/circleci-test-results
